Traceback (most recent call last):
  File "/root/default/Generative-Model/GAN/inference.py", line 99, in <module>
    main()
  File "/root/default/Generative-Model/GAN/inference.py", line 75, in main
    artifact = wandb.use_artifact(f"{project}/{config['model_version']}:latest", type="model")
KeyError: 'model_version'
